#!/usr/bin/env python3
"""
e001_packet_craft_and_parse.py

Packet crafting and parsing for photonic inference engine.

This script provides tools to:
1. Generate 802.1Q VLAN-tagged Ethernet frames for neuron activation encoding
2. Parse received packets and counter values
3. Validate packet structure before hardware testing
4. Simulate packet generation timing

Author: Andrew Campi
Date: December 19, 2025
"""

import struct
import time
import numpy as np
from typing import List, Tuple, Dict
from dataclasses import dataclass


# =============================================================================
# PACKET STRUCTURE CONSTANTS
# =============================================================================

# Ethernet frame sizes
ETH_HEADER_SIZE = 14  # bytes (6 dst + 6 src + 2 type)
VLAN_TAG_SIZE = 4     # bytes (2 TPID + 2 TCI)
MIN_PAYLOAD_SIZE = 46 # bytes (to reach 64-byte minimum)
FCS_SIZE = 4          # bytes (CRC, auto-generated by NIC)
MIN_FRAME_SIZE = 64   # bytes total (including VLAN tag)

# Ethernet constants
BROADCAST_MAC = b'\xff\xff\xff\xff\xff\xff'
TPID_8021Q = 0x8100   # 802.1Q VLAN tag identifier
ETHERTYPE_IPV4 = 0x0800  # Not used, but standard placeholder


# =============================================================================
# DATA STRUCTURES
# =============================================================================

@dataclass
class NeuronPacket:
    """Represents a single packet encoding neuron activation."""
    neuron_id: int
    layer_id: int
    activation_value: int  # Encoded as packet count
    timestamp: float = 0.0
    
    def __repr__(self):
        return f"NeuronPacket(n={self.neuron_id}, L={self.layer_id}, act={self.activation_value})"


@dataclass
class PacketBatch:
    """Batch of packets for one token inference."""
    packets: List[bytes]
    neuron_count: int
    layer_id: int
    total_bytes: int
    generation_time_us: float


# =============================================================================
# PACKET CRAFTING
# =============================================================================

def craft_ethernet_frame(
    dst_mac: bytes,
    src_mac: bytes,
    vlan_id: int,
    payload: bytes = None
) -> bytes:
    """
    Craft a complete 802.1Q VLAN-tagged Ethernet frame.
    
    Frame structure (64 bytes minimum):
    ┌──────────────────────────────────────┐
    │ Destination MAC (6 bytes)            │
    │ Source MAC (6 bytes)                 │
    │ TPID: 0x8100 (2 bytes)               │
    │ TCI: PCP|DEI|VLAN_ID (2 bytes)       │
    │ EtherType (2 bytes)                  │
    │ Payload (46 bytes, padded)           │
    │ [FCS: 4 bytes, added by NIC]         │
    └──────────────────────────────────────┘
    
    Args:
        dst_mac: Destination MAC address (6 bytes)
        src_mac: Source MAC address (6 bytes)
        vlan_id: VLAN ID (0-4095), encodes layer ID
        payload: Optional payload bytes
        
    Returns:
        Complete Ethernet frame (64 bytes, excluding FCS)
    """
    # Ethernet header (14 bytes)
    eth_header = dst_mac + src_mac
    
    # VLAN tag (4 bytes)
    # TCI format: 3 bits PCP | 1 bit DEI | 12 bits VLAN ID
    tci = vlan_id & 0x0FFF  # Ensure 12-bit VLAN ID
    vlan_tag = struct.pack('!HH', TPID_8021Q, tci)
    
    # EtherType (2 bytes)
    ethertype = struct.pack('!H', ETHERTYPE_IPV4)
    
    # Payload (46 bytes, padded with zeros)
    if payload is None:
        payload = b'\x00' * MIN_PAYLOAD_SIZE
    else:
        # Pad to minimum size
        if len(payload) < MIN_PAYLOAD_SIZE:
            payload = payload + b'\x00' * (MIN_PAYLOAD_SIZE - len(payload))
    
    # Assemble frame (FCS will be added by NIC hardware)
    frame = eth_header + vlan_tag + ethertype + payload
    
    # Verify size
    assert len(frame) == 64, f"Frame size {len(frame)} != 64 bytes"
    
    return frame


def generate_neuron_packets(
    neuron_id: int,
    activation_value: int,
    layer_id: int,
    src_mac: bytes,
    dst_mac: bytes = BROADCAST_MAC
) -> List[bytes]:
    """
    Generate packets for a single neuron.
    
    Activation encoding: activation_value=N → generate N identical packets
    
    Args:
        neuron_id: Neuron identifier (0-2879)
        activation_value: Neuron activation (0-255)
        layer_id: Current layer (0-31)
        src_mac: Source MAC address (host NIC)
        dst_mac: Destination MAC (usually broadcast)
        
    Returns:
        List of raw Ethernet frames (bytes)
    """
    packets = []
    
    for _ in range(activation_value):
        frame = craft_ethernet_frame(
            dst_mac=dst_mac,
            src_mac=src_mac,
            vlan_id=layer_id
        )
        packets.append(frame)
    
    return packets


def generate_token_packets(
    activation_vector: np.ndarray,
    layer_id: int = 0,
    src_mac: bytes = b'\x00\x1a\x2b\x3c\x4d\x5e'
) -> PacketBatch:
    """
    Generate all packets for one token inference.
    
    Args:
        activation_vector: Neuron activations (2880 values, 0-255)
        layer_id: Initial layer ID (typically 0)
        src_mac: Source MAC address
        
    Returns:
        PacketBatch with all packets and metadata
    """
    start_time = time.perf_counter()
    
    all_packets = []
    total_packets = 0
    
    for neuron_id, activation in enumerate(activation_vector):
        activation_int = int(np.clip(activation, 0, 255))
        
        if activation_int > 0:
            packets = generate_neuron_packets(
                neuron_id=neuron_id,
                activation_value=activation_int,
                layer_id=layer_id,
                src_mac=src_mac
            )
            all_packets.extend(packets)
            total_packets += len(packets)
    
    end_time = time.perf_counter()
    generation_time_us = (end_time - start_time) * 1e6
    
    batch = PacketBatch(
        packets=all_packets,
        neuron_count=len(activation_vector),
        layer_id=layer_id,
        total_bytes=total_packets * 64,
        generation_time_us=generation_time_us
    )
    
    return batch


# =============================================================================
# PACKET PARSING
# =============================================================================

def parse_ethernet_frame(frame: bytes) -> Dict:
    """
    Parse an 802.1Q Ethernet frame.
    
    Args:
        frame: Raw frame bytes (64 bytes minimum)
        
    Returns:
        Dictionary with parsed fields
    """
    if len(frame) < 64:
        raise ValueError(f"Frame too short: {len(frame)} bytes")
    
    # Parse header
    dst_mac = frame[0:6]
    src_mac = frame[6:12]
    tpid = struct.unpack('!H', frame[12:14])[0]
    
    # Check for VLAN tag
    if tpid == TPID_8021Q:
        tci = struct.unpack('!H', frame[14:16])[0]
        vlan_id = tci & 0x0FFF
        pcp = (tci >> 13) & 0x07
        dei = (tci >> 12) & 0x01
        ethertype = struct.unpack('!H', frame[16:18])[0]
        payload = frame[18:64]
    else:
        # No VLAN tag (shouldn't happen in our system)
        vlan_id = None
        pcp = None
        dei = None
        ethertype = tpid
        payload = frame[14:64]
    
    return {
        'dst_mac': dst_mac.hex(':'),
        'src_mac': src_mac.hex(':'),
        'vlan_id': vlan_id,
        'pcp': pcp,
        'dei': dei,
        'ethertype': ethertype,
        'payload_size': len(payload),
        'total_size': len(frame)
    }


def parse_counter_values(
    counter_array: np.ndarray,
    num_neurons: int = 2880,
    ports_per_switch: int = 96
) -> np.ndarray:
    """
    Parse hardware counter values into neuron activation array.
    
    With temporal multiplexing, multiple neurons map to each port.
    This function reconstructs the full neuron activation vector.
    
    Args:
        counter_array: Raw counter values from switch ports
        num_neurons: Total neurons in network (2880)
        ports_per_switch: Ports per switch (96)
        
    Returns:
        Neuron activation vector (2880 values)
    """
    # For now, assume simple 1:1 mapping for testing
    # TODO: Implement temporal multiplexing demux when hardware arrives
    
    if len(counter_array) < num_neurons:
        # Pad with zeros if needed
        activations = np.zeros(num_neurons, dtype=np.uint64)
        activations[:len(counter_array)] = counter_array
    else:
        activations = counter_array[:num_neurons]
    
    return activations


# =============================================================================
# VALIDATION & TESTING
# =============================================================================

def validate_packet_structure(frame: bytes) -> Tuple[bool, str]:
    """
    Validate that a packet has correct structure.
    
    Returns:
        (is_valid, error_message)
    """
    if len(frame) != 64:
        return False, f"Wrong size: {len(frame)} bytes (expected 64)"
    
    # Check VLAN tag
    tpid = struct.unpack('!H', frame[12:14])[0]
    if tpid != TPID_8021Q:
        return False, f"Missing VLAN tag: TPID={hex(tpid)}"
    
    # Check VLAN ID is in valid range
    tci = struct.unpack('!H', frame[14:16])[0]
    vlan_id = tci & 0x0FFF
    if vlan_id > 4095:
        return False, f"Invalid VLAN ID: {vlan_id}"
    
    return True, "OK"


def test_packet_generation_performance(
    num_neurons: int = 2880,
    avg_activation: float = 5.0,
    num_trials: int = 100
) -> Dict:
    """
    Benchmark packet generation performance.
    
    Target: <20 μs for 2,880 packets
    
    Returns:
        Performance statistics
    """
    print(f"\n{'='*60}")
    print(f"PACKET GENERATION PERFORMANCE TEST")
    print(f"{'='*60}")
    print(f"Neurons: {num_neurons}")
    print(f"Avg activation: {avg_activation}")
    print(f"Trials: {num_trials}")
    
    times = []
    packet_counts = []
    
    for trial in range(num_trials):
        # Generate random activation vector
        activations = np.random.poisson(avg_activation, num_neurons)
        activations = np.clip(activations, 0, 255).astype(np.uint8)
        
        # Generate packets
        batch = generate_token_packets(activations)
        
        times.append(batch.generation_time_us)
        packet_counts.append(len(batch.packets))
    
    stats = {
        'mean_time_us': np.mean(times),
        'std_time_us': np.std(times),
        'min_time_us': np.min(times),
        'max_time_us': np.max(times),
        'mean_packet_count': np.mean(packet_counts),
        'total_bytes_avg': np.mean(packet_counts) * 64
    }
    
    print(f"\nResults:")
    print(f"  Mean time:        {stats['mean_time_us']:.2f} μs")
    print(f"  Std dev:          {stats['std_time_us']:.2f} μs")
    print(f"  Min time:         {stats['min_time_us']:.2f} μs")
    print(f"  Max time:         {stats['max_time_us']:.2f} μs")
    print(f"  Avg packets:      {stats['mean_packet_count']:.0f}")
    print(f"  Avg total bytes:  {stats['total_bytes_avg']:.0f}")
    
    # Check against target
    target_us = 20.0
    if stats['mean_time_us'] <= target_us:
        print(f"\n✓ PASS: {stats['mean_time_us']:.2f} μs <= {target_us} μs target")
    else:
        print(f"\n✗ WARNING: {stats['mean_time_us']:.2f} μs > {target_us} μs target")
        print(f"  Slowdown factor: {stats['mean_time_us']/target_us:.2f}×")
    
    return stats


def test_packet_round_trip():
    """
    Test packet generation and parsing round-trip.
    """
    print(f"\n{'='*60}")
    print(f"PACKET ROUND-TRIP TEST")
    print(f"{'='*60}")
    
    # Generate test packet
    src_mac = b'\xaa\xbb\xcc\xdd\xee\xff'
    layer_id = 5
    
    packets = generate_neuron_packets(
        neuron_id=42,
        activation_value=3,
        layer_id=layer_id,
        src_mac=src_mac
    )
    
    print(f"\nGenerated {len(packets)} packets for neuron 42, layer {layer_id}")
    
    # Parse first packet
    parsed = parse_ethernet_frame(packets[0])
    
    print(f"\nParsed packet:")
    print(f"  Source MAC:   {parsed['src_mac']}")
    print(f"  Dest MAC:     {parsed['dst_mac']}")
    print(f"  VLAN ID:      {parsed['vlan_id']}")
    print(f"  EtherType:    {hex(parsed['ethertype'])}")
    print(f"  Payload size: {parsed['payload_size']} bytes")
    print(f"  Total size:   {parsed['total_size']} bytes")
    
    # Validate
    is_valid, msg = validate_packet_structure(packets[0])
    print(f"\nValidation: {msg}")
    
    if parsed['vlan_id'] == layer_id:
        print("✓ VLAN ID matches")
    else:
        print(f"✗ VLAN ID mismatch: expected {layer_id}, got {parsed['vlan_id']}")
    
    if parsed['src_mac'] == src_mac.hex(':'):
        print("✓ Source MAC matches")
    else:
        print(f"✗ Source MAC mismatch")
    
    return is_valid


def test_vlan_progression():
    """
    Test VLAN ID progression across layers (0 → 31).
    """
    print(f"\n{'='*60}")
    print(f"VLAN PROGRESSION TEST (32 LAYERS)")
    print(f"{'='*60}")
    
    src_mac = b'\x11\x22\x33\x44\x55\x66'
    
    print(f"\n{'Layer':<8} {'VLAN ID':<10} {'Valid':<8}")
    print(f"{'-'*30}")
    
    all_valid = True
    
    for layer in range(32):
        packets = generate_neuron_packets(
            neuron_id=0,
            activation_value=1,
            layer_id=layer,
            src_mac=src_mac
        )
        
        parsed = parse_ethernet_frame(packets[0])
        is_valid = parsed['vlan_id'] == layer
        
        status = "✓" if is_valid else "✗"
        print(f"{layer:<8} {parsed['vlan_id']:<10} {status:<8}")
        
        all_valid = all_valid and is_valid
    
    if all_valid:
        print(f"\n✓ All 32 layers have correct VLAN IDs")
    else:
        print(f"\n✗ Some layers have incorrect VLAN IDs")
    
    return all_valid


# =============================================================================
# MAIN TEST SUITE
# =============================================================================

def run_all_tests():
    """
    Run complete test suite before hardware validation.
    """
    print(f"\n{'#'*60}")
    print(f"#  PACKET CRAFTING & PARSING TEST SUITE")
    print(f"#  Research Phase 001 - Photonic Inference Engine")
    print(f"{'#'*60}")
    
    results = {}
    
    # Test 1: Round-trip
    results['round_trip'] = test_packet_round_trip()
    
    # Test 2: VLAN progression
    results['vlan_progression'] = test_vlan_progression()
    
    # Test 3: Performance
    perf_stats = test_packet_generation_performance()
    results['performance'] = perf_stats['mean_time_us'] <= 20.0
    
    # Summary
    print(f"\n{'='*60}")
    print(f"TEST SUMMARY")
    print(f"{'='*60}")
    
    for test_name, passed in results.items():
        if test_name != 'performance':
            status = "PASS ✓" if passed else "FAIL ✗"
            print(f"  {test_name:<25} {status}")
    
    all_passed = all(results.values())
    
    if all_passed:
        print(f"\n{'='*60}")
        print(f"  ALL TESTS PASSED ✓")
        print(f"  Ready for hardware validation!")
        print(f"{'='*60}\n")
    else:
        print(f"\n{'='*60}")
        print(f"  SOME TESTS FAILED ✗")
        print(f"  Review results above")
        print(f"{'='*60}\n")
    
    return all_passed


# =============================================================================
# EXAMPLE USAGE
# =============================================================================

if __name__ == "__main__":
    # Run complete test suite
    run_all_tests()
    
    # Example: Generate packets for a single token
    print(f"\n{'='*60}")
    print(f"EXAMPLE: Single Token Inference")
    print(f"{'='*60}")
    
    # Simulate input activations (2880 neurons)
    activations = np.random.randint(0, 10, size=2880, dtype=np.uint8)
    
    # Generate packets
    batch = generate_token_packets(activations, layer_id=0)
    
    print(f"\nGenerated packet batch:")
    print(f"  Neurons:          {batch.neuron_count}")
    print(f"  Total packets:    {len(batch.packets)}")
    print(f"  Total bytes:      {batch.total_bytes:,}")
    print(f"  Generation time:  {batch.generation_time_us:.2f} μs")
    print(f"  Layer ID:         {batch.layer_id}")
    
    # Calculate expected throughput
    if batch.generation_time_us > 0:
        tokens_per_sec = 1_000_000 / batch.generation_time_us
        print(f"  CPU throughput:   {tokens_per_sec:.0f} tokens/sec")
    
    print(f"\n{'='*60}\n")


""" Output:
python3 e001_packet_craft_and_parse.py 

############################################################
#  PACKET CRAFTING & PARSING TEST SUITE
#  Research Phase 001 - Photonic Inference Engine
############################################################

============================================================
PACKET ROUND-TRIP TEST
============================================================

Generated 3 packets for neuron 42, layer 5

Parsed packet:
  Source MAC:   aa:bb:cc:dd:ee:ff
  Dest MAC:     ff:ff:ff:ff:ff:ff
  VLAN ID:      5
  EtherType:    0x800
  Payload size: 46 bytes
  Total size:   64 bytes

Validation: OK
✓ VLAN ID matches
✓ Source MAC matches

============================================================
VLAN PROGRESSION TEST (32 LAYERS)
============================================================

Layer    VLAN ID    Valid   
------------------------------
0        0          ✓       
1        1          ✓       
2        2          ✓       
3        3          ✓       
4        4          ✓       
5        5          ✓       
6        6          ✓       
7        7          ✓       
8        8          ✓       
9        9          ✓       
10       10         ✓       
11       11         ✓       
12       12         ✓       
13       13         ✓       
14       14         ✓       
15       15         ✓       
16       16         ✓       
17       17         ✓       
18       18         ✓       
19       19         ✓       
20       20         ✓       
21       21         ✓       
22       22         ✓       
23       23         ✓       
24       24         ✓       
25       25         ✓       
26       26         ✓       
27       27         ✓       
28       28         ✓       
29       29         ✓       
30       30         ✓       
31       31         ✓       

✓ All 32 layers have correct VLAN IDs

============================================================
PACKET GENERATION PERFORMANCE TEST
============================================================
Neurons: 2880
Avg activation: 5.0
Trials: 100

Results:
  Mean time:        8712.60 μs
  Std dev:          183.59 μs
  Min time:         8371.25 μs
  Max time:         9165.00 μs
  Avg packets:      14394
  Avg total bytes:  921208

✗ WARNING: 8712.60 μs > 20.0 μs target
  Slowdown factor: 435.63×

============================================================
TEST SUMMARY
============================================================
  round_trip                PASS ✓
  vlan_progression          PASS ✓

============================================================
  SOME TESTS FAILED ✗
  Review results above
============================================================


============================================================
EXAMPLE: Single Token Inference
============================================================

Generated packet batch:
  Neurons:          2880
  Total packets:    13005
  Total bytes:      832,320
  Generation time:  8814.63 μs
  Layer ID:         0
  CPU throughput:   113 tokens/sec

============================================================
"""